module.exports = {
  lang : {
    en_US : {
      langName    : 'en_US',
      shoppingUrl : 'https://bloom-widgets-box01.salesfloor.net/tests/desktop',
      shoppingIp  : '?sf_ip=198.200.86.39',
      sf          : {
        backofficeUrl                       : 'https://holt-qa04.salesfloor.net/backoffice',
        storefrontUrl                       : 'https://holt-qa04.salesfloor.net/en_US/test_selling_store_mgr0?fromBackoffice=1',
        browseAssociatesOption              : 'span=Browse Associates',
        iNeedHelpWithMyOrderOption          : 'span=I need help with my order',
        iWantToSheduleAnAppointment         : 'span=I want to shedule an appointment',
        iMLookingForAnAssociateOption       : 'span=I’m looking for an Associate',
        iMLookingForABeautySpecialistOption : 'span=I’m looking for a Beauty Specialist',
        somethingElseOption                 : 'span=Something else!',
        ihaveProductQuestionsOption         : 'span=I have product questions',
        imLookingForStyleAdviceOption       : "span=I'm looking for style advice",
        bookAnAppointmentOptions            : 'span=Book an appointment',
        inAStoreOptions                     : 'span=In a store',
        onlineOptions                       : 'span=Online',
        getAnAnswerByEmailOptions           : 'span=Get an answer by email',
        bookOnlineAppointmentOption         : 'span=Book an online appointment',
        getAReplyBySmsOptions               : 'span=Get a reply by SMS',
        filterBySpecialtyBtn                : 'span=Filter by Specialty',
        filterByStoreBtn                    : 'span=Filter by Store',
        anyoneWouldWorkOption               : 'span=Anyone would work!',
        notFindPostalCodeMsg                : 'p=I couldn\'t find any locations based on your postal code.',
        yesBtn                              : 'span=Yes!',
        okLooksGoodOption                   : 'span=Ok, looks good',
        invalidPhoneNumberPopup             : 'div=Invalid phone number',
        cancelBtn                           : 'span=Cancel',
        invalidEmailPopup                   : 'div=Invalid email',
        imSorryToHearThatMsg                : "p=I'm sorry to hear that!",
        actuallyIllLeaveAMessage            : 'span=Actually, I’ll leave a message',
        liveChatOption                      : 'h2=Live Chat',
      }
    },
  },

  sf : {
    sales : {
      chatbotIframe : "iframe[id='sf-automat-companion']",
      chatbot       : '.button-hit-box',
      NextItemBtn   : "(//button[@aria-label='Next item'])[last()]",
      typeBtn       : "[aria-label='Type a message']",
    },
    iHaveProductQuestions : {
      listOfCategories                  : "//div[@style='visibility: visible;']/div/div/div[1]",
      categoryItem                      : "//div[@style='visibility: visible;']/div/div/div/div[1]",
      categoriesContinueBtn             : 'span=Continue',
      categoriesContinueDisabledBtn     : '//button[@disabled]',
      chatWithAnAssociateOptions        : "//span[contains(text(),'Chat with')]",
      listOfAssociates                  : "(//span[text()='Filter by Store']/following::div)[1]",
      findAnotherStoreBtn               : "//span[text()='Find another store']",
      chatPopupCloseBtn                 : "//button[@aria-label='Close Chat']",
      pastDateDisabledBtn               : '(//button[@disabled])[1]',
      storeNameLbl                      : '(//span[text()=\'My store\']/following::div/h2)[1]',
      anyoneWouldWorkSecondOption       : "(//span[text()='Anyone would work!'])[2]",
      ihaveProductQuestionsSecondOption : "(//span[text()='I have product questions'])[2]",
      selectATimeAndDateSecBtn          : '(//span[text()=\'Select a Time & Date\'])[2]',
      greenCheckMark                    : '.valid.check',
      makeThisMyStoreBtn                : '(//div[@data-test-e2e="Card"])[6]/div[2]/button',
      makeThisMyStore2ndBtn             : '(//div[@data-test-e2e="Card"])[7]/div[2]/button',
      confirmBtn                        : '//span[text()="My store"]/../../../div[2]/button[1]'
    },
    imLookingForAnAssociate : {
      firstAssociatesInList         : "(//p[text()=' Shoes'])[1]",
      connectBtn                    : 'span=Connect',
      connectWithAnyAssociateBtn    : 'p=Connect with any associate',
      chatWithReggieR               : 'span=Chat with Reggie R.',
      getAReplyBySMS                : 'span=Get a reply by SMS',
      getAReplyByEmail              : 'span=Get a reply by email',
      typeSendMessageBtn            : "[aria-label='Send Message']",
      selectATimeAndDate            : 'span=Select a Time & Date',
      calenderWithTimrSlot          : "(//button/span[contains(text(),'PM')])[last()] | (//button/span[contains(text(),'AM')])[last()]",
      associateContinueBtn          : 'span=Continue',
      emailTxt                      : "input[aria-label='Email address']",
      phoneTxt                      : "input[aria-label='Phone']",
      noThankYouOption              : 'span=No, thank you',
      emailBtn                      : "//span[text()='Email']",
      sMSBtn                        : "//span[text()='SMS']",
      noImGoodOption                : '//span[text()="No, I\'m good"]',
      NotNowOption                  : 'span=Not now',
      joinedTheChatMsg              : "//p[contains(text(),'joined the chat')]",
      leftTheChatMsg                : "//p[contains(text(),'left the chat')]",
      listOfRepsAssociatedWithStore : "[data-test-e2e='QuickReplies']"
    },
    liveChat : {
      userNameTxt              : "[placeholder='Username']",
      passwordTxt              : "[placeholder='Password']",
      signInBtn                : "[value='Sign In']",
      homePageTitle            : "//a[text()='Home']",
      toggleSwitchBtn          : '.lever',
      appointmentRequestOption : "//h2[text()='Appointment']",
      styleAdviceOption        : "//h2[text()='Style']",
      contactMeOption          : "//h2[text()='Contact']",
      availableNowOnLive       : "//h2[text()='Live Chat']/..//span[text()='Available Now']",
      unavailableOnLive        : "//h2[text()='Live Chat']/..//span[text()='Unavailable']"
    }
  }
};
